services:
  devagent-vnc:
    container_name: devagent-vnc
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "6080:6080"
      - "5900:5900"
    volumes:
      # Live-edit: mount repo root so Python can import llm/, tools/, etc.
      - ../:/app
    environment:
      # Make sure Python can import from /app when you exec into the container
      - PYTHONPATH=/app
    tty: true
    stdin_open: true
    restart: unless-stopped
    entrypoint: ["bash", "/app/agent/entrypoint.sh"]
    command: ["sleep", "infinity"]

volumes:
  # Placeholder if you later want to persist virtualenv or data
  # agent-venv:
  {}
